apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  nodeSelector:
    matchLabels: {}
  interfaces:
    - "^enp"
  externalIPs: true
  loadBalancerIPs: true
